apiVersion: rbac.authorization.k8s.io/v1
kind: Role
metadata:
  name: {{ include "karavan.fullname" . }}
  labels:
    {{- include "karavan.labels" . | nindent 4 }}
rules:
  - apiGroups: [""]
    resources: ["secrets", "configmaps", "serviceaccounts"]
    verbs: ["*"]
  - apiGroups: [""]
    resources: ["persistentvolumes", "persistentvolumeclaims"]
    verbs: ["*"]
  - apiGroups: [""]
    resources: ["pods", "pods/log", "pods/exec", "services", "replicationcontrollers"]
    verbs: ["*"]
  - apiGroups: ["apps"]
    resources: ["deployments"]
    verbs: ["*"]
  - apiGroups: ["networking.k8s.io"]
    resources: ["ingresses"]
    verbs: ["*"]
---
apiVersion: rbac.authorization.k8s.io/v1
kind: RoleBinding
metadata:
  name: {{ include "karavan.fullname" . }}
  labels:
    {{- include "karavan.labels" . | nindent 4 }}
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: Role
  name: {{ include "karavan.fullname" . }}
subjects:
  - kind: ServiceAccount
    name: {{ include "karavan.fullname" . }}
    namespace: {{ .Release.Namespace }}
